# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
    skip: [pylint,clang-format]
    autoupdate_schedule: monthly

exclude: ^(cmake/ECM|cmake/KDAB/|src/3rdparty/|code.dev.code-workspace)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-xml
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-json
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: check-executables-have-shebangs
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks:
  - id: clang-format
    exclude: (.json)
- repo: https://github.com/PyCQA/pylint
  rev: v3.2.7
  hooks:
  - id: pylint
    exclude: ^(.cmake-format.py|conan/conanfile.py)
    additional_dependencies: ["PySide2", "PySide6"]
- repo: https://github.com/hhatto/autopep8
  rev: v2.3.1
  hooks:
  - id: autopep8
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-lint
    exclude: (.py.cmake|Doxyfile.cmake|examples/flutter/)
  - id: cmake-format
    exclude: (.py.cmake|Doxyfile.cmake|examples/flutter/)
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.12.0
  hooks:
  - id: markdownlint
    entry: mdl
    language: ruby
    files: \.(md|mdown|markdown)$
    exclude: (docs/book/)
- repo: https://github.com/fsfe/reuse-tool
  rev: v4.0.3
  hooks:
  - id: reuse
    args: [--suppress-deprecation]
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.9.0-1
  hooks:
  - id: shfmt
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
